---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-dev-workspace
  namespace: nccl-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-datasets
  namespace: nccl-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
