---
apiVersion: v1
kind: Service
metadata:
  name: {app_name}
  namespace: {namespace}
  labels:
    app: {app_name}
spec:
  type: ClusterIP
  selector:
    app: {app_name}
  ports:
  - name: code-server
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: jupyter
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: tensorboard
    port: 6006
    targetPort: 6006
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {app_name}-vscode
  namespace: {namespace}
spec:
  to:
    kind: Service
    name: {app_name}
  port:
    targetPort: code-server
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {app_name}-jupyter
  namespace: {namespace}
spec:
  to:
    kind: Service
    name: {app_name}
  port:
    targetPort: jupyter
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {app_name}-tensorboard
  namespace: {namespace}
spec:
  to:
    kind: Service
    name: {app_name}
  port:
    targetPort: tensorboard
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
